name: base
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - certifi=2020.4.5.1
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - glib=2.56.2
  - graphite2=1.3.13
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2020.0
  - jasper=2.0.14
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
#  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - opencv=3.4.2
  - openssl=1.1.1f
  - pcre=8.43
  - pip=20.0.2
  - pixman=0.38.0
  - py-opencv=3.4.2
  - python=3.7.6
  - readline=7.0
  - setuptools=46.0.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - numpy==1.18.1
    - opencv-python==4.2.0.34
    - pandas==1.0.3
    - scikit-learn==0.22.1
    - tensorflow==1.15.0
    - tornado==3.2.1
    - tqdm==4.44.1
    - xgboost==1.0.2
    - gunicorn==20.0.4
    - python-dotenv==0.13.0
    - boto3==1.13.18
    - watchtower==0.7.3
    - coloredlogs
    - h5py
    - ujson
    - dlib
    - google-cloud-storage
    - pre-commit==1.14.2
    - scipy==1.4.1
    - joblib==0.14.1
    - memory-profiler
